update kernel config file

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -47,23 +47,7 @@ fi
 
 printf "\nBackup portage...\n"
 pushd "$(git rev-parse --show-toplevel)"
-
-printf "\nBackup kernel config...\n"
-config_dir=profiles/kernel.conf
-config_file=$config_dir/kernel-config-$(LANG=C lscpu | grep -i 'vendor' | awk -F ':' '{print $2}' | xargs)
-
-mkdir -p "${config_dir}"
-if [[ "${KCONF}" = "/proc/config" ]]; then
-    conf=$(gzip -d -c /proc/config)
-else
-    conf=$(cat "${KCONF}")
-fi
-
-echo "${conf}" | tail -n +4 | sed -E "/^CONFIG_(AS|GCC|CLANG|CC|LD|LLD)_VERSION/d" > ${config_file}
-
-printf "\nAdd to stage area....\n"
-git add "${config_file}" portage
-
+./scripts/generate-kernel-config.sh || die "failed to generate kernel config"
 popd
 
 printf "\nDone...\n"
